name: EffectMe
main: zoom\main
version: 1.1.3
api:
 - 3.0.0-ALPHA5
 - 3.0.0-ALPHA6
 - 3.0.0-ALPHA7
 - 3.0.0-ALPHA8
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
load: POSTWORLD
author: HTTPS7Team
